[package]
name = "the-index"
version = "0.3.0"
description = "The Index character archive"
authors = ["VeyrStudio"]
edition = "2021"

[lib]
name = "the_index_lib"
crate-type = ["staticlib","cdylib","rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["clock"] }
rfd = "0.15"
base64 = "0.22"
sha2 = "0.10"
ureq = { version = "2.12", features = ["json"] }
